# Generated by Django 4.0 on 2022-01-04 17:07

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_source_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=orders.models.get_directory_path, validators=[orders.models.max_file_size]),
        ),
    ]
