# Generated by Django 4.0 on 2022-01-04 00:58

from django.db import migrations, models
import django.db.models.deletion
import twitter_images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField()),
                ('image', models.ImageField(upload_to=twitter_images.models.get_upload_folder_name)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('twitter_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_profiles.twitterprofile')),
            ],
        ),
    ]
