# Generated by Django 4.0 on 2022-01-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterimage',
            name='average_color',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='twitterimage',
            name='dominant_color',
            field=models.JSONField(null=True),
        ),
    ]
