# Generated by Django 4.0 on 2022-01-04 18:08

import collages.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_alter_order_source_image'),
        ('twitter_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage_image', models.ImageField(upload_to=collages.models.get_upload_folder_name)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('twitter_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_profiles.twitterprofile')),
            ],
        ),
    ]
